CREATE TABLE USERS
(
    USER_ID    BIGINT UNSIGNED        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(50)            NOT NULL,
    PASSWORD   VARCHAR(80)            NOT NULL,
    CREATED_AT DATETIME DEFAULT NOW() NOT NULL,
    UPDATED_AT DATETIME               NULL
) charset = 'utf8mb4';

CREATE INDEX idx_users_email ON USERS (EMAIL);